//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomor_Whatsapp_Sender.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SavedMessage {
            get {
                return ((string)(this["SavedMessage"]));
            }
            set {
                this["SavedMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MessageTemplate {
            get {
                return ((string)(this["MessageTemplate"]));
            }
            set {
                this["MessageTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("عزيزي المشترك\n%CustomerName%\n\nنود إعلامك بأن اشتراكك" +
            " في خدمة الإنترنت مع مكتب النمور للانترنت سينتهي قريبًا.\n\nتاريخ انتهاء الاشتراك: %Expir" +
            "ation%\nنوع الاشتراك: %BundleName%\n\nتبقى على انتهاء اشتراكك: %يوم% يوم | %ساعة%" +
            " ساعة | %دقيقة% دقيقة")]
        public string TemplateActive {
            get {
                return ((string)(this["TemplateActive"]));
            }
            set {
                this["TemplateActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("عزيزي المشترك\n%CustomerName%\n\nنود إعلامك بأن اشتراكك" +
            " في خدمة الإنترنت مع مكتب النمور للانترنت منتهي الصلاحية.\n\n\nتاريخ انتهاء الاشتراك: %Expir" +
            "ation%\nنوع الاشتراك: %BundleName%\n\nانتهى اشتراكك قبل: %يوم% يوم | %ساعة% ساعة" +
            " | %دقيقة% دقيقة")]
        public string TemplateExpired {
            get {
                return ((string)(this["TemplateExpired"]));
            }
            set {
                this["TemplateExpired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedDays {
            get {
                return ((string)(this["SelectedDays"]));
            }
            set {
                this["SelectedDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsSchedulerRunning {
            get {
                return ((bool)(this["IsSchedulerRunning"]));
            }
            set {
                this["IsSchedulerRunning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime NextScheduledTime {
            get {
                return ((global::System.DateTime)(this["NextScheduledTime"]));
            }
            set {
                this["NextScheduledTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ExpirationStatus {
            get {
                return ((int)(this["ExpirationStatus"]));
            }
            set {
                this["ExpirationStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:3111/send?number={phone}&message={message}")]
        public string WhatsAppApiUrl {
            get {
                return ((string)(this["WhatsAppApiUrl"]));
            }
            set {
                this["WhatsAppApiUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LocationCoords {
            get {
                return ((string)(this["LocationCoords"]));
            }
            set {
                this["LocationCoords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SendLocation {
            get {
                return ((bool)(this["SendLocation"]));
            }
            set {
                this["SendLocation"] = value;
            }
        }
    }
}
